# Hugo build configuration for Netlify
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

[build]
command = "npm run build:preview"
publish = "public"

[build.environment]
GO_VERSION = "1.22.2"
HUGO_VERSION = "0.155.3"
NODE_VERSION = "22"

[context.production]
command = "npm run build:production"
